import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { Toaster } from "@/components/ui/sonner";
import { ModalProvider } from "@/providers/modal-provider";

const font = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <TRPCReactProvider>
          <EdgeStoreProvider>
            {children}
            <ModalProvider />
            <Toaster richColors position="top-center" />
          </EdgeStoreProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
